### ISSUE TITLE
Remove scatter plots 

### ISSUE THREAD

**Issue by F-said** [tpham16/TKH-Social-Media-Engagement-Analytics#44]
**Problem**

In [youtube_eda7](https://github.com/tpham16/TKH-Social-Media-Engagement-Analytics/blob/main/sprint7_eda/youtube_eda7.ipynb) there are a couple of scatter plots for time-series data. 

![image](https://github.com/tpham16/TKH-Social-Media-Engagement-Analytics/assets/26397102/5362878b-0596-4765-967d-0d531fa7fe04)

These would be better suited as line-plots (which are actually already plotted below).

![image](https://github.com/tpham16/TKH-Social-Media-Engagement-Analytics/assets/26397102/621f2123-05f8-4272-8525-91532fe711d4)

**Expected Output**

To prevent confusion, we should remove the mentioned scatter plots for time series data and instead keep the line plots.

**Definition of done**

Scatter plot time-series removed, line-plots added where necessary, committed, pushed, and merged.

**Comment by JZunaRepo** [comment]
Scatter plots deleted from youtube_eda.ipynb
